const _mockData = [
  { title: "9 -Nine- Haruiro Harukoi Harunokaze", url: "7xlHGsmbQQg" },
  { title: "9 -Nine- Haruiro Harukoi Harunokaze", url: "6K5F9MBcUc8" },
  { title: "9 -Nine- Kokonotsu Kokonoka Kokonoiro", url: "pp4O_6JB_iU" },
  { title: "9 -Nine- Sorairo Sorauta Soranooto", url: "Bpuq-XmKVHM" },
  { title: "9 -Nine- Shinshou", url: "_wXztMb7BI8" },
  { title: "9 -Nine- Sorairo Sorauta Soranooto", url: "vKgeqjecF2w" },
  { title: "9 -Nine- Kokonotsu Kokonoka Kokonoiro", url: "dGBIL56a4tA" },
  { title: "9 -Nine- Yukiiro Yukihana Yukinoato", url: "LH0yFFPBTuc" },
  { title: "9 -Nine- Yukiiro Yukihana Yukinoato", url: "LNCPBVcI1WI" },
  { title: "9 -Nine- Yukiiro Yukihana Yukinoato", url: "0GmSG_5g5i8" },
  { title: "Ai Kiss 2", url: "su5x77TDUho" },
  { title: "Aikotoba", url: "UnVnIITvA0k" },
  { title: "Akatsuki Yureru Koi Akari", url: "5wYva2gAgF8" },
  { title: "Amatsutsumi", url: "BCR94YzpPsU" },
  {
    title: "Amazing Grace -What Color Is Your Attribute?-",
    url: "nl_fBSYY8e8",
  },
  { title: "Angel Beats! -1st beat-", url: "rPVcGanIaMQ" },
  { title: "Aoi Tori", url: "PcR8FcYEFw4" },
  { title: "Aonatsu Line", url: "8s6A7qLXrEk" },
  { title: "Ao no Kanata no Four Rhythm", url: "c74D_ug--K4" },
  { title: "Ao no Kanata no Four Rhythm EXTRA1", url: "P_V7vi2Sxxk" },
  { title: "Aqua", url: "ScVHtS4glTo" },
  { title: "AstralAir no Shiroki Towa", url: "6VnrZTRR4_c" },
  { title: "AstralAir no Shiroki Towa Finale", url: "ZuMw2KPwWqg" },
  { title: "Cafe Stella to Shinigami no Chou", url: "D7MVqK_jo-E" },
  { title: "Cafe Stella to Shinigami no Chou", url: "yuODPcJgYew" },
  { title: "Cafe Stella to Shinigami no Chou", url: "8Er0xP1IUTA" },
  { title: "Chrono Clock", url: "rZ8jkQxvp74" },
  { title: "CLANNAD", url: "tCV7yyImQFk" },
  { title: "Clover Day's", url: "nkwf2R5Z8H4" },
  { title: "Cross Concerto", url: "LBseltRw2uM" },
  { title: "D.C.4 ~Da Capo 4~", url: "7sQSihFvHJM" },
  { title: "D.C. II ~Da Capo II~ Dearest Marriage", url: "cT4nlzmQ66g" },
  { title: "D.C. II ~Da Capo II~ Fall in Love", url: "_VVy5HbGyo0" },
  { title: "Dekinai Watashi ga, Kurikaesu.", url: "6EmYZHD9Kos" },
  { title: "Dracu-Riot!", url: "aAsPEEOTbgQ" },
  { title: "DraPri Guu-ta-life", url: "c4vWWKW3-j8" },
  { title: "DraPri Guu-ta-life 2", url: "1TT4ZwCi0Sw" },
  { title: "Einstein Yori Ai o Komete", url: "Jq3z0_Ho3J4" },
  { title: "Einstein Yori Ai o Komete", url: "k47AE29qyNQ" },
  { title: "E School Life", url: "SvdTuEeN5Co" },
  { title: "Flowers -Le Volume sur Automne-", url: "ceKGAh0R2tk" },
  { title: "Flowers -Le Volume sur Été-", url: "y_ytaVM0_Qk" },
  { title: "Flowers -Le Volume sur Hiver-", url: "36lAVsXO7XQ" },
  { title: "Flowers -Le Volume sur Printemps-", url: "qPU-VnW3kwU" },
  { title: "Fortissimo EXS//Akkord:Nachsten Phase", url: "1SBQn1ZQFYg" },
  { title: "Fortissimo EXS//Akkord:Nachsten Phase", url: "LcbcGREEl8c" },
  { title: "Fortissimo EXS//Akkord:Nachsten Phase", url: "gDFz7URxTv8" },
  { title: "Fuyukara, Kururu.", url: "0LxrzgjWDew" },
  { title: "Garasu Hime to Kagami no Juusha", url: "ekFreTJ3xx8" },
  { title: "Giniro Haruka", url: "uebSF0PQd24" },
  { title: "Grisaia no Rakuen", url: "QHLvJ1tbsHE" },
  { title: "HajiLove -Making * Lovers-", url: "P6iaZSEcqCU" },
  { title: "Hamidashi Creative", url: "GD-ZqpHVMHY" },
  { title: "Hana Hime * Absolute!", url: "BdOL3Y9ANRQ" },
  { title: "Hana no No ni Saku Utakata no", url: "onO6d5HCYQM" },
  { title: "Hanasaki Work Spring!", url: "j-a-p5VoO7k" },
  { title: "Happiness! 2 Sakura Celebration", url: "TbReSus6evU" },
  { title: "Happy Live, Show Up!", url: "4XZAnoMqLFQ" },
  { title: "Hapymaher -Fragmentation Dream-", url: "oP_E9entrGU" },
  { title: "Haruka na sora", url: "M8ZRxzN671A" },
  { title: "Hatsujou Sprinkle", url: "mwQqAGLIfiY" },
  { title: "Hatsukoi 1/1", url: "Jx2LIAUN4H0" },
  { title: "Hatsukoi * Syndrome", url: "T-EWjID46ZI" },
  { title: "Hatsuyuki Sakura", url: "d-VpQDv_tbw" },
  { title: "Hatsuyuki Sakura", url: "6Y3k9blLKzY" },
  { title: "Hikari no Umi no Apeiria", url: "BlXVyzhW728" },
  { title: "Hoshi no Ne Sanctuary", url: "fzld1T1raoQ" },
  { title: "Hoshi Ori Yume Mirai", url: "SRnQo9UVgrc" },
  { title: "Hoshizora no Memoria Eternal Heart", url: "QcRcKWA8hpM" },
  { title: "Houkago Cinderella", url: "1cZ48dqAcMU" },
  { title: "Imouto ga Boku o Neratteru", url: "qnxbANejw70" },
  { title: "Imouto no Katachi", url: "wSj6_bB4LNY" },
  { title: "Irotoridori no Hikari", url: "J2rEP8sU40w" },
  { title: "Irotoridori no Hikari", url: "cHoZO6QqmgA" },
  { title: "IxSHE Tell", url: "_8cAzY7xjxE" },
  { title: "Kakenuke★Seishun Sparking!", url: "YoijjGmfRIo" },
  { title: "Kakenuke★Seishun Sparking!", url: "pC91EvljiZE" },
  { title: "Kanzume Shoujo no Shuumatsu Sekai", url: "bWaAw7nybWg" },
  { title: "Kimagure Temptation", url: "UNDUFp-GIbk" },
  { title: "Kimi to Kanojo to Kanojo no Koi", url: "1FU928-GTU4" },
  { title: "Kimi to Mezameru Ikutsuka no Houhou", url: "0NoX7NW9thU" },
  { title: "Kimi to Tsunagaru Koi Flag", url: "u5DI7T-PGxg" },
  { title: "Kimi to Yumemishi", url: "uzVMLDRYRJY" },
  { title: "Kimi to Yumemishi", url: "WaP3Vf9QKiI" },
  { title: "Kin'iro Loveriche", url: "lSxdYupXOlI" },
  { title: "Kin'iro Loveriche", url: "O-41WrK6zgc" },
  { title: "Kin'iro Loveriche -Golden Time-", url: "rdKdFswYQzY" },
  { title: "Koiken Otome", url: "UYOp-DqJyEc" },
  { title: "Koiseyo Imouto Banchou", url: "ReMd9gUBLDM" },
  { title: "Koi to Koi Suru Utopia", url: "ZiXoQh-jnxc" },
  { title: "Koi to Senkyo to Chocolate", url: "xUwhN5xoJY0" },
  { title: "Kokorone=Pendulum!", url: "NohiJeTqSZw" },
  { title: "Kud Wafter", url: "tKEXxRczymg" },
  { title: "Kud Wafter", url: "4bsSBHP9_pA" },
  { title: "Little Busters!", url: "XGSTRM_t0i8" },
  { title: "LOOPERS", url: "5G0JKS3dMMI" },
  { title: "Maitetsu - Last Run!!", url: "zrCHeOH4pOE" },
  { title: "Making*Lovers", url: "4705SQQFR5U" },
  { title: "Mashiro Iro Symphony: *mutsu no hana", url: "eD8d4EvNpC4" },
  { title: "Material Brave", url: "KcqtqfMW-84" },
  { title: "Miagete Goran, Yozora no Hoshi o", url: "zqGpHOLGIlo" },
  { title: "Miagete Goran, Yozora no Hoshi o", url: "dzQNWtJD8aw" },
  { title: "Miagete Goran, Yozora no Hoshi o: Fine Days", url: "fFUNd5olsQI" },
  { title: "Mirai Nostalgia", url: "GzP1GSIXs_s" },
  { title: "Mirai Radio to Jinkou-bato", url: "LMW27kwdSLA" },
  { title: "Mirai Radio to Jinkou-bato", url: "lEU4ir-srcg" },
  { title: "Natural Vacation", url: "NFxQfbjKy_A" },
  { title: "NEW Love plus", url: "qstK5RJBZcM" },
  { title: "Newton to Ringo no Ki", url: "5My3PEvHhI4" },
  { title: "Nora to Oujo to Noraneko Heart 2", url: "IP-OG3vm9h8" },
  { title: "NukiTashi1", url: "UuIhJrFaaPg" },
  { title: "NukiTashi1", url: "ZpqMX3gtvjQ" },
  { title: "NukiTashi2", url: "xBa1aCEJ0eE" },
  {
    title: "Ore no Sugata ga, Toumei ni!? Invisible to Suuki na Unmei",
    url: "WGm2Ag-JNjU",
  },
  { title: "Oshi no Love yori Koi no Love", url: "iHezuj7isyQ" },
  { title: "Parquet", url: "7H7W8KLplL4" },
  { title: "Pieces / Wataridori no Somnium", url: "dwUmle3WN4M" },
  { title: "Pieces / Yurikago no Canaria", url: "Oa3Vvd1MVjQ" },
  { title: "Primal x Hearts", url: "RKR4fmdWcAE" },
  { title: "Qualia ~Yakusoku no Kiseki~", url: "nY27RNx0Bac" },
  { title: "Raspberry cube", url: "Ow34q-aNhHA" },
  { title: "Realive", url: "3z_efCiu6zc" },
  { title: "Re CATION　～Melty Healing～", url: "tD1wJBiu_sY" },
  { title: "Re:LieF", url: "cT3wbp17Ano" },
  { title: "Ren'ai, Karichaimashita", url: "xkzfrlZSO3s" },
  { title: "Ren'ai x Royale", url: "rYUlY05gRII" },
  { title: "Ren'ai x Royale", url: "rudbX-hFQc4" },
  { title: "Rewrite", url: "Ne-4_Bz0wAg" },
  { title: "Rewrite", url: "S9M04iL2qok" },
  { title: "Riddle Joker", url: "t0a7b_QHA24" },
  { title: "Riddle Joker", url: "efm2usyZXRc" },
  { title: "Ryuusei World Actor", url: "s_YKjYzAX3M" },
  { title: "Sakura iro Dreamer", url: "HiLnCY9qjSo" },
  { title: "Sakura Iro, Mau Koro ni", url: "F5y917xdBoc" },
  {
    title: "Sakura, Moyu. -As the Night's, Reincarnation-",
    url: "X2e1vPBJjcA",
  },
  {
    title: "Sakura, Moyu. -As the Night's, Reincarnation-",
    url: "nhAm1qvFrv4",
  },
  {
    title: "Sakura, Moyu. -As the Night's, Reincarnation-",
    url: "NlanFppt-_0",
  },
  { title: "Sakura no Kumo * Scarlet no Koi", url: "ze7LofS9bC0" },
  { title: "Sakura no Uta", url: "5-9sqUZZXaY" },
  { title: "Sanoba Witch", url: "W7ARsYs-Gq0" },
  {
    title: "Secret Agent ~Kishi Gakuen no Shinobi Naru Mono~",
    url: "kSsdYHIRDsY",
  },
  { title: "Seishun Fragile", url: "0y9sdeJjbaY" },
  { title: "Senren * Banka", url: "MtiAJc_F2y0" },
  { title: "Senren * Banka", url: "JMRJgTWyLH8" },
  { title: "Senren * Banka", url: "PKkdGdY9Mdg" },
  { title: "Shiraha Kirameku Koi Shirabe", url: "m4NN_Xs4BUU" },
  {
    title: "Shukusei no Girlfriend 3 -The Destiny Star of Girlfriend-",
    url: "TxdBZvX9nLU",
  },
  {
    title: "Shukusei no Girlfriend -The Destiny Star of Girlfriend-",
    url: "iuOBb-gmULo",
  },
  { title: "Sora ni Kizanda Parallelogram", url: "x12UsxAEagI" },
  {
    title: "Sorceress * Alive! ~the World's End Fallen Star~",
    url: "G8TcTTxDO6g",
  },
  { title: "Steins;Gate", url: "qXC-tvQdQzA" },
  { title: "Steins;Gate 0", url: "I012yI2Kzqg" },
  { title: "Study § Steady", url: "glhuedWyXVw" },
  { title: "Subarashiki Hibi", url: "dQ5g1Va7CjI" },
  { title: "Subarashiki Hibi", url: "trr9kRV_vus" },
  { title: "Subarashiki Hibi", url: "hod2dbnK0Fc" },
  { title: "Subarashiki Hibi", url: "NFa_PhZKA-k" },
  { title: "Subarashiki Hibi", url: "zL1B74qaN-c" },
  { title: "Subarashiki Hibi", url: "Il2UQC848A8" },
  { title: "Sugar * Style", url: "Tx-8WmSV2Ko" },
  { title: "Summer Pockets", url: "EWdTEw7Shog" },
  { title: "Summer Pockets", url: "aLzvey6DTRg" },
  { title: "Summer Pockets REFLECTION BLUE", url: "bkX7DAw59p0" },
  { title: "Tamayura Mirai", url: "DXOl9ek5dJw" },
  { title: "Tsukihime -A Piece of Blue Glass Moon-", url: "dw19QCjQ2ks" },
  { title: "Tsukikage no Simulacre", url: "WOXjZLxZIRQ" },
  { title: "Tsuki no Kanata de Aimashou", url: "uUAVj_SRtCU" },
  {
    title: "Tsuki no Kanata de Aimashou: Sweet Summer Rainbow",
    url: "C3cdYa7Uaig",
  },
  {
    title: "Tsuyuchiru Letter ~Umi to Shiori ni Amaoto o~",
    url: "5ldQheKaTYY",
  },
  { title: "Utawarerumono Futari no Hakuoro", url: "ISE3tr_bWFU" },
  { title: "Utawarerumono Itsuwari no kamen", url: "STg4Ya8bEFo" },
  { title: "Utawarerumono Prelude to the Fallen", url: "MiufiO2cYAE" },
  { title: "Wagamama High Spec", url: "OkrW4XW--fI" },
  { title: "Wagamama High Spec OC", url: "0BHz5Z2vaf8" },
  { title: "Wakaba-iro no Quartet", url: "5NNrcdkxg9M" },
  { title: "Watashi ga Suki nara Suki tte Itte!", url: "eoM3JesiQdg" },
  { title: "White Album 2", url: "i588G4isJr8" },
  { title: "White Album 2", url: "N-26_1aAC9Q" },
  { title: "White Album 2", url: "CT4nJL9vo9s" },
  { title: "White Album 2", url: "LgHrk6qhJ3Q" },
  { title: "D.C. II ~Da Capo II~", url: "KSSiSPiZvY0" },
  { title: "Witch's Garden", url: "lwHTExD_C-A" },
  { title: "Yorite Konoha wa Kurenai ni", url: "xiNNeoWajvk" },
  { title: "Your diary", url: "f_h_V6vkFYQ" },
  { title: "Yuki iro Sign", url: "NcZLC80esoQ" },
  { title: "Yume to Iro de Dekiteiru", url: "THGFIMHGhEI" },
  { title: "Yumeutsutsu Re:Master", url: "lD-yUC87-BQ" },
  { title: "Material Brave Ignition", url: "s2CuXxF-NqQ" },
  { title: "Sora no Mukou de Sakimasu you ni", url: "8EaOBNstM9A" },
  { title: "Utawarerumono Prelude to the Fallen", url: "g4QfKoNY4lA" },
  { title: "Karumaruka * Circle", url: "p02nbi9ic4g" },
  { title: "Karumaruka * Circle", url: "on6h4tR0WNQ" },
  { title: "Hatsuyuki Sakura", url: "8krwU0O7290" },
  { title: "Kisaragi Gold ★ Star", url: "Fam05xNvPKw" },
  { title: "Hanasaki Work Spring!", url: "_898ZGuaRko" },
  { title: "Hanasaki Work Spring!", url: "lVxARvMeW_4" },
  { title: "Twinkle ☆ Crusaders -Passion Star Stream-", url: "51r4mVjyDP8" },
  { title: "Izayoi no Fortuna", url: "KqAxHlu90I8" },
  { title: "Koiken Otome ~Revive~", url: "zfmryeuQksw" },
  { title: "Hoshizora no Memoria", url: "bptWcFr1f9I" },
  { title: "Irotoridori no Sekai", url: "YnlFg4Pkzzc" },
  { title: "Akai Hitomi ni Utsuru Sekai", url: "bPCJHX5UpSg" },
  { title: "Akai Hitomi ni Utsuru Sekai", url: "AEAnzo6adCI" },
  { title: "Akai Hitomi ni Utsuru Sekai", url: "IW0FSXp4Ckk" },
  { title: "D.C. III ~Da Capo III~", url: "NFKpY7B1lGo" },
  { title: "D.C. III ~Da Capo III~", url: "B2ZbmLjoz4U" },
  { title: "D.C. III ~Da Capo III~", url: "r7gqSDIAmP8" },
  { title: "D.C. III ~Da Capo III~", url: "sB4WQL01w90" },
  { title: "Otome＊Domain", url: "gUQJ1jNpzBw" },
  { title: "Kimi to Tsunagaru Koi Flag", url: "TAM_Q8GgLI4" },
  { title: "Floral Flowlove", url: "IhhbGEgNcOo" },
  { title: "Chrono Clock", url: "7lqQCMYgOd4" },
  { title: "Karenai Sekai to Owaru Hana", url: "oNZ0DPLGvRA" },
  { title: "Amatsutsumi", url: "rfbKdkmxTug" },
  { title: "Hapymaher -Fragmentation Dream-", url: "PxQ8N3Y2JvQ" },
  { title: "Aoi Tori", url: "_bfsF-phjpM" },
  { title: "Dracu-Riot!", url: "g5oKmtuESrk" },
  { title: "Dracu-Riot!", url: "iDffHCyfzIo" },
  { title: "Hidamari Basket", url: "rTFSFQbKRGc" },
  { title: "Kamidanomi Shisugite Ore no Mirai ga Yabai.", url: "U5YAXe3AlWo" },
  { title: "Yoake Mae yori Ruri Iro na", url: "xi02y4u5b7k" },
  { title: "Daitoshokan no Hitsujikai", url: "PoH7iAiip8M" },
  { title: "Kono Oozora ni, Tsubasa o Hirogete", url: "Qpd5IbP9cAg" },
  {
    title: "Miagete Goran, Yozora no Hoshi o: Interstellar Focus",
    url: "W1a8hZJ-ABE",
  },
  { title: "Mirai Nostalgia", url: "cHOg32NmZM4" },
  { title: "Haruiro Ouse", url: "sXfpjeD4upo" },
  { title: "Areas ~Koi Suru Otome no 3H~", url: "9rrAd3HuLtM" },
  { title: "Ren'ai Katei Kyoushi Rurumi Coordinate!", url: "HI89jIUQIFA" },
  { title: "Kadenz Fermata//Akkord:Fortissimo", url: "_d9x3KNTtYY" },
  { title: "Strawberry Nauts", url: "sEaPJ6D-_mA" },
  {
    title: "Meguru Kisetsu no Yakusoku to, Tsunaida Sono Te no Nukumori to",
    url: "SgkHkrhwRe8",
  },
  { title: "Hatsuyuki Sakura", url: "WPW_XOtXe4M" },
  { title: "Lamunation!", url: "hQkWqCTdojg" },
  { title: "Hapymaher", url: "6FoKNRjs5rM" },
  { title: "AstralAir no Shiroki Towa", url: "ahnyE-0g7FI" },
  { title: "Fortissimo EXS//Akkord:Nachsten Phase", url: "YGdtYdIiy3o" },
  { title: "Hikari no Umi no Apeiria", url: "XYrtkq4qBiA" },
  { title: "Noble ☆ Works", url: "qKvcrUU7Lq8" },
  { title: "Pure Girl", url: "InRhIGEWeS4" },
  { title: "Little Busters!", url: "viJ3MGkrwtY" },
  { title: "Magica Ride", url: "aCinJZQTGmc" },
  { title: "Schwarzesmarken", url: "hwflY16_YtU" },
  { title: "G-senjou no Maou", url: "UB13dHaDsEk" },
  { title: "Kanojo no Seiiki", url: "d9r0EcKnM68" },
  { title: "11eyes -Tsumi to Batsu to Aganai no Shoujo-", url: "jBrfcD_q2m8" },
  { title: "Sorcery Jokers", url: "TBG1bSywCJM" },
  { title: "Sorcery Jokers", url: "PwVkvWNjATE" },
  { title: "DeepOne", url: "hQYGfbyw-LE" },
  {
    title: "Shukusei no Girlfriend 2 -The Destiny Star of Girlfriend-",
    url: "ASXCLzE4-Zc",
  },
  { title: "Giniro Haruka", url: "hpPCYnWhzCc" },
  { title: "Kami-machi Sana-chan", url: "8GBoLt9PJTI" },
  { title: "Hataraku Otona no Ren'ai Jijou", url: "hUII7id4MNg" },
  {
    title: "Deatte 5-fun wa Ore no Mono! Jikan Teishi to Atropos",
    url: "rpo8SQwh_nI",
  },
  { title: "Fuyu Uso -Snow World End-", url: "vU_crC3kxIU" },
  { title: "Ryuusei World Actor Badge", url: "0ofi5dkuq2E" },
  { title: "Sorcery Jokers", url: "lgc2EsH_wFM" },
  {
    title: "Tsuki no Kanata de Aimashou: Sweet Summer Rainbow",
    url: "S44nCHI2n_s",
  },
  {
    title: "Sorceress * Alive! ~the World's End Fallen Star~",
    url: "bmF1emgv5cQ",
  },
  { title: "Nanairo Reincarnation", url: "JKOiKtbo5Vs" },
  { title: "Mary Skelter: Nightmares", url: "J0hNDWcZVHM" },
  { title: "Mary Skelter: Nightmares 2", url: "iTwdyEC62DU" },
  { title: "Mary Skelter: Nightmares Final", url: "CtJ3OPhGdEU" },
  { title: "Evenicle 2", url: "NZXsSJFZI50" },
  { title: "Imouto no Seiiki", url: "BHx3tANYyTw" },
  { title: "Imouto no Seiiki", url: "TxVgKp47t8w" },
  { title: "Dare mo Shiranai Sora e no Namida", url: "cZoVKVf9kyg" },
  { title: "HaremKingdom", url: "ZWHw263bkL4" },
  { title: "Tayutama 2 -you're the only one-", url: "SedIZ_RS2PM" },
  { title: "Tayutama 2 -you're the only one-", url: "-twzpp7C9ms" },
  { title: "Inochi no Spare", url: "1fRg5mIXAOw" },
  { title: "Rensou Relation", url: "rzeYDuZmom0" },
  { title: "Kodomo no Asobi", url: "Jx2b4m_UI8g" },
  { title: "Unmei Senjou no Phi", url: "iQVIUXeCFZE" },
  { title: "Akiba's Trip", url: "U7HcZCzycs4" },
  { title: "Sekai to Sekai no Mannaka de", url: "DxhJSXX9ncM" },
  { title: "Magical Charming!", url: "fqrNkcBQMX0" },
  { title: "Diamic Days", url: "7zhoQGJro-Q" },
  { title: "Nursery Rhyme", url: "sdk9vDdxjm4" },
  { title: "Akiba's Trip 2", url: "XGUpmTNpXzo" },
  { title: "Haruruminamoni!", url: "GTIt_TbYPJY" },
  { title: "Kizuna Kirameku Koi Iroha", url: "4TqsS-jgdFs" },
  { title: "Air", url: "vrOcqetSVEs" },
  { title: "Shiraha Kirameku Koi Shirabe", url: "m4NN_Xs4BUU" },
  { title: "Kizuna Kirameku Koi Iroha -Tsubaki Renka-", url: "OTpT19cO5NA" },
  { title: "Neko-nin exHeart 3", url: "MuKUh0lxHsc" },
  {
    title:
      "Heroine wa Tomodachi Desu ka? Koibito Desu ka? Soretomo Tomefure Desu ka?",
    url: "FvImlPwUvJ8",
  },
  { title: "Senkou no Clarias", url: "XkS3T30r3Ms" },
  { title: "Ano Hi no Tabibito, Fureau Mirai", url: "sFZbSNlfsdg" },
  { title: "Ama Ane -My Sweet Sister-", url: "48uFIqcvgEg" },
  { title: "Otome ga Musubu Tsukiyo no Kirameki", url: "nBQxATAeIxE" },
  {
    title: "Otome ga Musubu Tsukiyo no Kirameki Fullmoon Days",
    url: "Tbm8MpJ9oXE",
  },
  { title: "Haru Uso -Passing Memories-", url: "3_HhtxMxjaw" },
  { title: "Natsu Uso -Ahead of the Reminiscence-", url: "iF172V0H5gE" },
  { title: "Aki Uso -The Only Neat Thing To Do-", url: "OmZy1kP-LUc" },
  {
    title: "Hikari no Umi no Apeiria ~Casablanca no Kishi~",
    url: "0TNjJ2Y5ePc",
  },
  { title: "Koi ga Saku Koro Sakura Doki", url: "SNKaw_i-0dk" },
  { title: "Watashi ga Suki nara Suki tte Itte!", url: "3JPb7f7lyNU" },
  { title: "Onii-chan, Asa made Zutto Gyutte Shite!", url: "IzzSbwaahGA" },
  { title: "Docchi no i ga Suki Desu ka?", url: "TuJfTWqAlVE" },
  { title: "World Election", url: "VWz7l2VbkfA" },
  { title: "Happy Margaret!", url: "9M1p8y_zXZk" },
  { title: "Happy Margaret!", url: "N6Cu_gsJ4Pg" },
  { title: "Wiz Anniversary", url: "xxGmeblDcUg" },
  { title: "Hoshizora no Memoria", url: "hY4hX6IbuTg" },
  { title: "Hoshizora no Memoria Eternal Heart", url: "VFT8yy-q60U" },
  { title: "Irotoridori no Sekai", url: "azg2XeWPmNs" },
  { title: "Kunado Kokuki", url: "0tynIJ0tgH8" },
  { title: "Areas ~Sora ni Utsusu Kimi to no Sekai~", url: "zsV0VXJKR4w" },
  { title: "Areas ~Sora ni Utsusu Kimi to no Sekai~", url: "EamHAzfD04c" },
  { title: "Sorakoi", url: "JhoxcSJosb0" },
  { title: "Sorakoi", url: "yFjFZ77OyFc" },
  { title: "Making*Lovers", url: "6GsfhrP7Dpw" },
  { title: "Haruoto Alice * Gram", url: "RRyhgyX6LsI" },
  { title: "Hoshizora e Kakaru Hashi", url: "KCefHFwtg0Q" },
  { title: "Hoshizora e Kakaru Hashi AA", url: "xOzIi4lixbk" },
  { title: "Haruru Minamo ni!", url: "qb5Z0Ib505o" },
  { title: "Tsukikage no Simulacre", url: "dvobRrghezQ" },
  { title: "Sumire", url: "2pxohcsk9I0" },
  { title: "1/7 no Mahoutsukai", url: "_5qP1PWZ0wQ" },
  { title: "Minamijuujisei Renka", url: "RcWmcP9f7jE" },
  { title: "Hana Hime * Absolute!", url: "LrKy7LTASZo" },
  { title: "Natsu ni Kanaderu Bokura no Uta", url: "xpNthJx20HQ" },
  {
    title: "Jewelry Hearts Academia -We will wing wonder world-",
    url: "IoVk5_pVH5g",
  },
  {
    title: "Jewelry Hearts Academia -We will wing wonder world-",
    url: "vpas-duCP78",
  },
  { title: "Koiiro Soramoyou", url: "ZiyoE7h0YM4" },
  { title: "Sakura no Uta", url: "sxtj-JkMlHA" },
  { title: "Meikei no lupercalia", url: "VM8ZqmwPZ74" },
  { title: "Sakura no Uta", url: "UWbVdWJ0iDo" },
  { title: "Sakura no Uta", url: "HAufR6YrSNc" },
  { title: "Sakura no Uta", url: "_fy7MlN_ZYc" },
  { title: "Sakura no Uta", url: "auu-PIE2hWw" },
  { title: "Hakuchuumu no Aojashin", url: "8pdEGmTA12A" },
  { title: "Hakuchuumu no Aojashin", url: "VTkzKmiPKDc" },
  { title: "Hakuchuumu no Aojashin", url: "G21T4EDXuHU" },
  { title: "Hakuchuumu no Aojashin", url: "ytKJN6myP4U" },
  { title: "Sakura no Kumo * Scarlet no Koi", url: "BDHfbLRfx9E" },
  { title: "Euphoria", url: "116zkTqCOhM" },
  { title: "Sakura no Uta", url: "hKSEceYzTSg" },
  { title: "Sousaku Kanojo no Ren'ai Koushiki", url: "VW6XRZexyS4" },
  { title: "Sousaku Kanojo no Ren'ai Koushiki", url: "oNWqXduASIk" },
  { title: "Akiyume kukuru", url: "CLGsh_v_kDw" },
  { title: "Tsuki Kagerou", url: "XKWgYX05_Pc" },
  { title: "Tsuki Kagerou", url: "bpevRSDnMJI" },
  { title: "Shuffle", url: "78YHbx1FMGw" },
  { title: "Shuffle", url: "SmKvye8KhKs" },
  { title: "Harumade kururu", url: "zBO9gaUU1Sw" },
  { title: "Natsukumo yururu", url: "xdGFuD2TkW4" },
  { title: "Hentai Prison", url: "LODU8y6ZM48" },
  { title: "Ouchi ni Kaeru made ga Mashimaro desu", url: "5V96uvNyEMc" },
  { title: "Kunado Kokuki", url: "MgdhOfriP68" },
  { title: "Nekopara Vol.1", url: "bVtSUIiawEs" },
  { title: "Nekopara Vol.2 ", url: "MvkI-6Vw87k" },
  { title: "Nekopara Vol.3", url: "RgVPFDEPLj0" },
  { title: "Nekopara Vol.4", url: "hHSkFls-rgM" },
  { title: "Katakoi no Tsuki Extra", url: "P96uYt1yMmI" },
  { title: "Futamata Ren'ai", url: "arCkpmIqAlg" },
  { title: "Shoujo Activity", url: "cRVDFy6GmRE" },
  { title: "Oretachi ni Tsubasa wa nai", url: "bOl9T7K1y7E" },
  { title: "AMBITIOUS MISSION", url: "vXFdn2u5r-0" },
  { title: "Owaru sekai to birthday", url: "dzK8b3m_XMI" },
  { title: "Unless Terminalia", url: "B5Agjv6v3jM" },
  { title: "H2O √after and another", url: "YMnkn9VkKOs" },
  { title: "H2O", url: "qjVL_X3zhT0" },
  { title: "Happy Live, Show Up!", url: "Zv0fcp0gZOg" },
  { title: "Colorful Kiss ~12 ko no Mune Kyun!~", url: "KHh_E_9tUao" },
  { title: "Sayonara o Oshiete", url: "M1etCfEGyHE" },
  { title: "Kizuato", url: "kQSE6-1ltgo" },
  { title: "Owaru sekai to birthday", url: "3AE5oC3VgsA" },
  { title: "Natsukumo Yururu", url: "XpBJTZqrOsY" },
  { title: "doHna:doHna -Issho ni Warui Koto o Shiyou-", url: "mvBYEjHIomw" },
  { title: "Hare Nochi Kitto Nanohana Biyori", url: "7I92XqxjXaA" },
  { title: "Hare Nochi Kitto Nanohana Biyori", url: "MgG3bWa-mVI" },
  { title: "Ao no Kanata no Four Rhythm EXTRA2", url: "XnxKFvEVI8E" },
  { title: "LOOPERS", url: "b1k6QcWxu4Q" },
  { title: "Tsuki ni Yorisou Otome no Sahou", url: "XMt5fOyZpWc" },
  { title: "Little Busters!", url: "NJ1maDVtIx8" },
  { title: "Little Busters!", url: "rdpqerzaosA" },
  { title: "Muv Luv Alternative", url: "HCLQn-OCdEA" },
  { title: "PRIMAL×HEARTS2", url: "FQSvToMi_7I" },
  { title: "Aiyoku no Eustia", url: "r2U9ifulhJ8" },
  { title: "Enkou Shoujo 2 ~JK Idol Marin no Baai~", url: "_bqdOSDRCfs" },
  { title: "Kin'iro Loveriche", url: "8pTSesHjo_M" },
  { title: "Kimi no Hitomi Ni Hit Me", url: "sebOYAylH4g" },
  { title: "Amaekata wa Kanojo Nari ni", url: "LhkB97LOb5w" },
  { title: "PrismRhythm", url: "j-1EPGWGv7c" },
  { title: "Figu@mate", url: "aKo0DI9xpjA" },
  { title: "Koiimo Sweet ☆ Days", url: "Yipp0cCc4Mo" },
  { title: "Sen no Hatou, Tsukisome no Kouki", url: "cha0ocLSnlk" },
  {
    title: "Sen no Hatou, Tsukisome no Kouki -Hana Akari-",
    url: "2xO3dv-xYAo",
  },
  { title: "Sen no Hatou, Tsukisome no Kouki", url: "OZPf2wlEYNs" },
  { title: "Amaemi-longing for you-", url: "_4ER0vraCNQ" },
  { title: "Maggot baits", url: "Y7y6oatrstY" },
  { title: "Dead days", url: "Zd-3-c05y7w" },
  { title: "Aoi Sora no Camus", url: "8_phvkTYnCU" },
  { title: "Itadaki Jangarian R", url: "qfcVbyi2fZw" },
  { title: "Dreamin' Her -Boku wa, Kanojo no Yume o Miru", url: "r0iN3VufvOM" },
  { title: "Sakura no mori Dreamers", url: "SQhVzkyF5-I" },
  { title: "Kujiragami no Tearstilla", url: "Z1oPvebAD44" },
  { title: "Kujiragami no Tearstilla", url: "TP072bynaaw" },
  { title: "Hanidebi! Honey Devil", url: "MVOUZtLYAMg" },
  { title: "Irotoridori no Sekai", url: "VmQoyRU0rzw" },
  { title: "Suisou Ginka no Istoria", url: "1vWn-D-cJbY" },
  { title: "Clover Day's", url: "0kABC1LQfA8" },
  { title: "Ikinari Anata ni Koishiteiru", url: "PjahAfI_h-s" },
  { title: "Kimi ga Nozomu Eien", url: "NN78yhD3yRQ" },
  { title: "Parquet", url: "5zv-vGo3c1Q" },
  { title: "PRIMAL×HEARTS2", url: "bJ4LFnk785g" },
  { title: "White Album", url: "hGTGbJVYVVs" },
  { title: "Sakura no Toki", url: "InqcYvdLyAw" },
  { title: "Himawari no kyoukai to nagai natsuyasumi", url: "ms1D8ZPK_Ig" },
  { title: "Natsu no Iro no Nostalgia", url: "K2F3UZnLY2Y" },
  { title: "White Album", url: "VrFrcFYD6Q0" },
  { title: "Yoru Meguru, Bokura no Maigo Kyoushitsu", url: "PRr26Ox8kPs" },
  { title: "Yoru Meguru, Bokura no Maigo Kyoushitsu", url: "m4jjFhaf98c" },
  { title: "Tapestry -you will meet yourself-", url: "XoDaPPRdtt0" },
  { title: "Kami no Rhapsody", url: "A_IBc5Wvcf4" },
  { title: "Hanairo Heptagram", url: "HA_GqFKcZrk" },
  { title: "Gaku ☆ Ou -The Royal Seven Stars-", url: "GlMRYGVrvTs" },
  { title: "Futagoza no Paradox", url: "RFAxb54-udM" },
  { title: "Sekai to Sekai no Mannaka de", url: "DbwbUzq-tB0" },
  { title: "Tayutama -Kiss on My Deity-", url: "8opwf-oqaEw" },
  { title: "Tayutama -Kiss on My Deity-", url: "QotubIKF8j0" },
  { title: "Tayutama -Kiss on My Deity-", url: "TsDDK6wW8SE" },
  { title: "Tayutama -It's Happy Days-", url: "kLcL4w78EPY" },
  { title: "Himawari", url: "fTkwNLMVsPI" },
  {
    title: "Yumekoi ~Yume Miru Mahou Shoujo to Koi no Jumon~",
    url: "PiUGzFIhi2k",
  },
  { title: "Kimi e Okuru, Sora no Hana", url: "N8QP3wmUESg" },
  {
    title: "Nyan Café Macchiato ~Neko ga Iru Café no Ecchi Jijou~",
    url: "ZGpEYEiLbIs",
  },
  {
    title: "Kimi to Boku to no Kishi no Hibi -Rakuen no Chevalier-",
    url: "a_RS8IZzCrM",
  },
  { title: "Kimi no Tonari de Koishiteru!", url: "ITIxnUPVgIU" },
  {
    title: "Kimi no Tonari de Koishiteru! ~The Respective Happiness~",
    url: "Jn4RcVdfNhE",
  },
  { title: "Grisaia no Kajitsu -LE FRUIT DE LA GRISAIA-", url: "mm0vyVNIXAA" },
  {
    title: "Grisaia no Meikyuu -LE LABYRINTHE DE LA GRISAIA-",
    url: "MWyWy94QA-E",
  },
  { title: "Grisaia no Rakuen -LE EDEN DE LA GRISAIA-", url: "xu9N0rtV4lc" },
  { title: "PRIMAL×HEARTS2", url: "TWag87slcrk" },
  { title: "Golden Hour", url: "wDkPac9qc3I" },
  {
    title: "Yumekoi ~Yume Miru Mahou Shoujo to Koi no Jumon~",
    url: "WLhDSkqRURI",
  },
  { title: "Tomoyo After -It's a Wonderful Life-", url: "TmTnjGfVdpM" },
  {
    title: "Magicalic Sky High ~Soratobu Houki ni Omoi o Nosete~",
    url: "NI3SOSmpSpo",
  },
  { title: "G.I.B. Girls in Black", url: "h59uw2werLk" },
  { title: "Lunaris Filia", url: "bM6-OEDTFrk" },
  { title: "LOVELY QUEST", url: "wTP-I_n1o7M" },
  { title: "MeltyMoment", url: "IDVQlY7A2ig" },
  { title: "Koi x Shin Ai Kanojo", url: "AdPtQZNzBRY" },
  { title: "Koi x Shin Ai Kanojo", url: "5XFW7t8K_jE" },
  { title: "Koi x Shin Ai Kanojo", url: "Zuf9ZBahOLE" },
  { title: "Makai Tenshi Djibril -Episode 2-", url: "v37wC8KfY4E" },
  { title: "Makai Tenshi Djibril -Episode 3-", url: "OIUWW_PtALw" },
  { title: "Makai Tenshi Djibril 4", url: "AD8f0yPgSw8" },
  {
    title: "Makai Tenshi Djibril 5 // Sengoku Tenshi Djibril",
    url: "ZyDj1M5gAXA",
  },
  { title: "Innocent Girl", url: "r6YjHtyUEY8" },
  { title: "Fate/stay night", url: "VsYZy1g8jGs" },
  {
    title: "Fate/stay night [Realta Nua] Unlimited Blade Works",
    url: "om3n10-lGMQ",
  },
  { title: "Fate/stay night [Realta Nua] Heaven's Feel", url: "gtmdnB95Uxc" },
  {
    title: "World Love Organization // W. L. O. Sekai Ren'ai Kikou",
    url: "NA45jQssO2I",
  },
  {
    title:
      "Sora Tobu Hitsuji to Manatsu no Hana -When Girls Wish Upon A Star.-",
    url: "RmlQac97eH4",
  },
  { title: "Sakura, Sakimashita", url: "R3TbWckmn44" },
  { title: "Sakura, Sakimashita", url: "lYFpvx0hMew" },
  { title: "Haruka Kanata", url: "H0aPVAPslWg" },
  { title: "Gakuen Butou no Folklore", url: "HqSPuovm5m4" },
  { title: "Kamitsure ~7 no Nijou Fushigi~", url: "ITA9xf3T2ko" },
  { title: "Katahane", url: "qcSUoNVN6po" },
  { title: "Katahane", url: "dEozIPft74I" },
  { title: "your diary+H", url: "HA2dFPx7L-Q" },
  {
    title:
      "Yurameku Kokoro ni Michita Sekai de, Kimi no Yume to Yokubou wa Kanau ka",
    url: "IEbwwm6TReg",
  },
  { title: "Flyable Heart", url: "OhEL8htphww" },
  { title: "Flyable CandyHeart", url: "WrStbtvZBl0" },
  { title: "Akane Iro ni Somaru Saka", url: "t9Fr4s1N4Rk" },
  { title: "Aozora no Mieru Oka", url: "QtigaTr8_hU" },
  { title: "Yume to Iro de Dekiteiru", url: "j4kWHA4ABSM" },
  { title: "Chiisana Kanojo no Serenade", url: "4tfAojtZMKU" },
  { title: "Chiisana Kanojo no Serenade", url: "93_UY1Z2U0k" },
  {
    title: "Gleam Garden no Shoujo -Witch in Gleamgarden-",
    url: "XyTp1Iifb0A",
  },
  { title: "Prism ◇ Recollection!", url: "VrNThSUd_RM" },
  {
    title: "Tokeijikake no Ley Line -Asagiri ni Chiru Hana-",
    url: "7U-lFSOlDiw",
  },
  {
    title: "Tokeijikake no Ley Line -Zan'ei no Yoru ga Akeru Toki-",
    url: "ciZvqfBCjEU",
  },
  {
    title: "Tokeijikake no Ley Line -Tasogaredoki no Kyoukaisen-",
    url: "qKd6tRo72ps",
  },
  { title: "Konata yori Kanata made", url: "QE-gDvdjcHs" },
  { title: "Konata yori Kanata made 2", url: "V9jkECzwOEo" },
  { title: "Reminiscence", url: "-nb77ljQ8YQ" },
  { title: "Reminiscence Re:Collect", url: "sqwPulKxn0w" },
  { title: "Natsu no Owari no Nirvana", url: "vfclg4zNhgU" },
  { title: "Cocoro@Function!", url: "ZwZnDgI4vsY" },
  { title: "Cocoro@Function!", url: "XgB7qxyWJVo" },
  { title: "Hitotsu Tobashi Renai", url: "JX-mOzpCFQw" },
  { title: "Innocent Bullet -The False World-", url: "Z_aIUGaZWgU" },
  {
    title: "Shoujo Shiniki Shoujo Tengoku -The Garden of Fifth Zoa-",
    url: "ZS1tvb_cFdg",
  },
  { title: "Berry's", url: "NReqFmzKAH4" },
  { title: "Amairo * Islenauts", url: "kHrNOxcT1lc" },
  { title: "Timepiece Ensemble", url: "vhrUYIEcrKg" },
  { title: "1/2 summer", url: "4FbgDhpyMvI" },
  { title: "Tsukiakari Lunch", url: "Ip8mMfIX6hw" },
  { title: "Fureraba -Friend to Lover-", url: "gOxfW38m3aI" },
  { title: "Girls Be Ambitious!", url: "6P0BMNIOGwM" },
  { title: "Zannen na Ore-tachi no Seishun Jijou", url: "--LddcEicEc" },
  { title: "Ame Koi", url: "sC7eP5nUpDE" },
  { title: "Harukaze Sensation", url: "oKQ1F6rAfRE" },
  { title: "Daitoshokan no Hitsujikai -Dreaming Sheep-", url: "0dz7jmWrpMg" },
  { title: "Majo Koi Nikki", url: "LRP6paRRSco" },
  { title: "Majo Koi Nikki", url: "-RgTxNi8He0" },
  { title: "Majo Koi Nikki", url: "HbXvVG2IFDA" },
  { title: "Majo Koi Nikki", url: "lO54loCtXkM" },
  { title: "Mayoeru Futari to Sekai no Subete", url: "L_vBR1ShQow" },
  { title: "Koisuru Shimai no Sextet", url: "2lpIcRnBelM" },
  { title: "Koi Suru Doll to Omoi no Kiseki", url: "jm-1p0JkkAI" },
  { title: "Tsukumo no Tsuki", url: "FAY2HXIU818" },
  { title: "Scramble Lovers", url: "3Cwx0YkMMMQ" },
  { title: "Ore no Kanojo no Uraomote", url: "ilg-DU_Jwns" },
  { title: "D.C. III P.P. Da Capo III Platinum Partner", url: "fgsWj-fDU8w" },
  { title: "PRETTY x CATION", url: "O_KgGAD6QmI" },
  { title: "Boku to Koi Suru Ponkotsu Akuma", url: "Q3YsIWqr_1c" },
  { title: "Pure x Connect", url: "oiMk32k40CY" },
  { title: "ALIA's CARNIVAL", url: "tlZZi4XX0aY" },
  { title: "Sorairo Innocent", url: "qE4JHdS0Smw" },
  { title: "Panical Confusion", url: "zZjKWsNmnLI" },
  { title: "Tou no Shita no Exercitus", url: "_Z7jOzsmx60" },
  { title: "Seisai no Resonance", url: "mlzwFhB9RjQ" },
  { title: "Koko kara Natsu no Innocence", url: "6nXHFHn_714" },
  { title: "D.S. -Dal Segno-", url: "43P5bh5i1Lg" },
  { title: "D.S. i.F. -Dal Segno- in Future", url: "EPa7KxFlbjI" },
  { title: "Hanikami Clover", url: "ZeMYoSBr8C4" },
  {
    title: "Shukufuku no Kane no Ne wa, Sakurairo no Kaze to Tomo ni",
    url: "sGX0dJXmK7o",
  },
  { title: "Liber 7 Eigou no Owari o Matsu Kimi e", url: "99Kbf0Ty8wU" },
  { title: "Sakura no Mori Dreamers 2", url: "iKKjPJ3JupM" },
  { title: "Tojita Sekai no Tori Colony", url: "-UVUavvuNjI" },
  { title: "ExE", url: "q80xAjugZbc" },
  { title: "ExE", url: "JqRggTDg5Bo" },
  { title: "Ever 17", url: "xkRaemCX4dQ" },
  { title: "Bra-Ban!", url: "_Y7_mpi930Q" },
  { title: "Bra-Ban!", url: "4RPnD4MX580" },
  { title: "Tenshin Ranman - Lucky or Unlucky!?", url: "Pqisib2bAb8" },
  { title: "Tenshin Ranman - Lucky or Unlucky!?", url: "dBcHtoPW9oQ" },
  { title: "Natsuzora Kanata", url: "tZex-pAybl4" },
  { title: "Hello,good bye", url: "TWB643L7qso" },
  { title: "Sharin no Kuni, Himawari no Shoujo", url: "k6RHKVQC4ak" },
  {
    title: "Meguru Kisetsu no Yakusoku to, Tsunaida Sono Te no Nukumori to",
    url: "SgkHkrhwRe8",
  },
];

const _mockAllTitle = _mockData.map((c) => c.title);
const _uniqueArray = (items) => [...new Set(items)];
const _mockAllTitleWithKey = _uniqueArray(_mockAllTitle).map((c) => {
  return {
    title: c,
  };
});
export { _mockData, _mockAllTitle, _mockAllTitleWithKey };
