const _mockData = [
  { title: "Senren * Banka", url: "MtiAJc_F2y0" },
  { title: "9 -Nine- Sorairo Sorauta Soranooto", url: "vKgeqjecF2w" },
  { title: "9 -Nine- Yukiiro Yukihana Yukinoato", url: "LH0yFFPBTuc&t" },
  { title: "Hatsuyuki Sakura", url: "t0EF64SW3bs" },
  { title: "Hanasaki Work Spring!", url: "j-a-p5VoO7k" },
  { title: "Hatsuyuki Sakura", url: "6Y3k9blLKzY" },
  { title: "Sen no Hatou, Tsukisome no Kouki", url: "cha0ocLSnlk" },
  { title: "Hana Hime * Absolute!", url: "BdOL3Y9ANRQ" },
  { title: "Yumeutsutsu Re:Master", url: "lD-yUC87-BQ" },
  { title: "Kimi to Kanojo to Kanojo no Koi", url: "1FU928-GTU4" },

  { title: "Summer Pockets REFLECTION BLUE", url: "bkX7DAw59p0" },
  { title: "Tsukikage no Simulacre", url: "WOXjZLxZIRQ" },
  { title: "Imouto no Katachi", url: "wSj6_bB4LNY" },
  { title: "Primal x Hearts", url: "RKR4fmdWcAE" },
  { title: "Aqua", url: "ScVHtS4glTo" },
  { title: "Koiseyo Imouto Banchou", url: "ReMd9gUBLDM" },
  { title: "Hoshi no Ne Sanctuary", url: "fzld1T1raoQ" },
  { title: "Sakura no Kumo * Scarlet no Koi", url: "ze7LofS9bC0" },
  { title: "Flowers -Le Volume sur Printemps-", url: "qPU-VnW3kwU" },
  { title: "Flowers -Le Volume sur Été-", url: "y_ytaVM0_Qk" },

  { title: "Imouto ga Boku o Neratteru", url: "qnxbANejw70" },
  { title: "Chrono Clock", url: "rZ8jkQxvp74" },
  { title: "Fortissimo EXS//Akkord:Nachsten Phase", url: "1SBQn1ZQFYg" },
  { title: "Flowers -Le Volume sur Automne-", url: "ceKGAh0R2tk" },
  { title: "Imouto no Okage de Motesugite Yabai", url: "Gyf5lD0fhc8" },
  { title: "Flowers -Le Volume sur Hiver-", url: "36lAVsXO7XQ" },
  { title: "Irotoridori no Hikari", url: "J2rEP8sU40w" },
  {
    title: "Sakura, Moyu. -As the Night's, Reincarnation-",
    url: "X2e1vPBJjcA",
  },
  {
    title: "Sakura, Moyu. -As the Night's, Reincarnation-",
    url: "nhAm1qvFrv4",
  },
  {
    title: "Sakura, Moyu. -As the Night's, Reincarnation-",
    url: "NlanFppt-_0",
  },

  { title: "White Album 2", url: "i588G4isJr8" },
  { title: "Aoi Tori", url: "PcR8FcYEFw4" },
  { title: "Amatsutsumi", url: "BCR94YzpPsU" },
  { title: "AstralAir no Shiroki Towa Finale", url: "ZuMw2KPwWqg" },
  { title: "AstralAir no Shiroki Towa", url: "6VnrZTRR4_c" },
  { title: "Hoshizora no Memoria Eternal Heart", url: "QcRcKWA8hpM" },
  { title: "D.C. II ~Da Capo II~ Dearest Marriage", url: "cT4nlzmQ66g" },
  { title: "Fortissimo EXS//Akkord:Nachsten Phase", url: "LcbcGREEl8c" },
  { title: "D.C. II ~Da Capo II~ Fall in Love", url: "_VVy5HbGyo0" },
  { title: "Irotoridori no Hikari", url: "cHoZO6QqmgA" },
];

const _mockAllTitle = [
  "Senren * Banka",
  "9 -Nine- Sorairo Sorauta Soranooto",
  "9 -Nine- Yukiiro Yukihana Yukinoato",
  "Hatsuyuki Sakura",
  "Hanasaki Work Spring!",
  "Hatsuyuki Sakura",
  "Sen no Hatou, Tsukisome no Kouki",
  "Hana Hime * Absolute!",
  "Yumeutsutsu Re:Master",
  "Kimi to Kanojo to Kanojo no Koi",
  "Summer Pockets REFLECTION BLUE",
  "Tsukikage no Simulacre",
  "Imouto no Katachi",
  "Primal x Hearts",
  "Aqua",
  "Koiseyo Imouto Banchou",
  "Hoshi no Ne Sanctuary",
  "Sakura no Kumo * Scarlet no Koi",
  "Flowers -Le Volume sur Printemps-",
  "Flowers -Le Volume sur Été-",
  "Imouto ga Boku o Neratteru",
  "Chrono Clock",
  "Fortissimo EXS//Akkord:Nachsten Phase",
  "Flowers -Le Volume sur Automne-",
  "Imouto no Okage de Motesugite Yabai",
  "Flowers -Le Volume sur Hiver-",
  "Irotoridori no Hikari",
  "Sakura, Moyu. -As the Night's, Reincarnation-",
  "Sakura, Moyu. -As the Night's, Reincarnation-",
  "Sakura, Moyu. -As the Night's, Reincarnation-",
  "White Album 2",
  "Aoi Tori",
  "Amatsutsumi",
  "AstralAir no Shiroki Towa Finale",
  "AstralAir no Shiroki Towa",
  "Hoshizora no Memoria Eternal Heart",
  "D.C. II ~Da Capo II~ Dearest Marriage",
  "Fortissimo EXS//Akkord:Nachsten Phase",
  "D.C. II ~Da Capo II~ Fall in Love",
  "Irotoridori no Hikari",
  "Little Busters!",
  "Clover Day's",
  "Giniro Haruka",
  "Tsuyuchiru Letter ~Umi to Shiori ni Amaoto o~",
];

export { _mockData, _mockAllTitle };
